#
# Wizard autogenerated makefile.
# DO NOT EDIT, use the ade_user.mk file instead.
#

# Constants automatically defined by the selected modules
ade_DEBUG = 1

# Our target application
TRG += ade

ade_PREFIX = "/usr/bin/avr-"

ade_SUFFIX = ""

ade_SRC_PATH = ade

ade_HW_PATH = ade

# Files automatically generated by the wizard. DO NOT EDIT, USE ade_USER_CSRC INSTEAD!
ade_WIZARD_CSRC = \
	bertos/cpu/avr/drv/timer_avr.c \
	bertos/drv/meter_ade7753.c \
	bertos/io/kfile.c \
	bertos/mware/formatwr.c \
	bertos/drv/timer.c \
	bertos/mware/event.c \
	bertos/cpu/avr/drv/ser_avr.c \
	bertos/drv/ser.c \
	bertos/mware/hex.c \
	bertos/mware/parser.c \
	bertos/struct/hashtable.c \
	bertos/verstag.c \
	#

# Files automatically generated by the wizard. DO NOT EDIT, USE ade_USER_PCSRC INSTEAD!
ade_WIZARD_PCSRC = \
	bertos/mware/formatwr.c \
	#

# Files automatically generated by the wizard. DO NOT EDIT, USE ade_USER_CPPASRC INSTEAD!
ade_WIZARD_CPPASRC = \
	 \
	#

# Files automatically generated by the wizard. DO NOT EDIT, USE ade_USER_CXXSRC INSTEAD!
ade_WIZARD_CXXSRC = \
	 \
	#

# Files automatically generated by the wizard. DO NOT EDIT, USE ade_USER_ASRC INSTEAD!
ade_WIZARD_ASRC = \
	 \
	#

ade_CPPFLAGS = -D'CPU_FREQ=(14745600UL)' -D'ARCH=(ARCH_DEFAULT)' -D'WIZ_AUTOGEN' -I$(ade_HW_PATH) -I$(ade_SRC_PATH) $(ade_CPU_CPPFLAGS) $(ade_USER_CPPFLAGS)
#ade_CPPFLAGS = -D'CPU_FREQ=(8000000UL)' -D'ARCH=(ARCH_DEFAULT)' -D'WIZ_AUTOGEN' -I$(ade_HW_PATH) -I$(ade_SRC_PATH) $(ade_CPU_CPPFLAGS) $(ade_USER_CPPFLAGS)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
ade_LDFLAGS = $(ade_CPU_LDFLAGS) $(ade_WIZARD_LDFLAGS) $(ade_USER_LDFLAGS)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
ade_CPPAFLAGS = $(ade_CPU_CPPAFLAGS) $(ade_WIZARD_CPPAFLAGS) $(ade_USER_CPPAFLAGS)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
ade_CSRC = $(ade_CPU_CSRC) $(ade_WIZARD_CSRC) $(ade_USER_CSRC)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
ade_PCSRC = $(ade_CPU_PCSRC) $(ade_WIZARD_PCSRC) $(ade_USER_PCSRC)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
ade_CPPASRC = $(ade_CPU_CPPASRC) $(ade_WIZARD_CPPASRC) $(ade_USER_CPPASRC)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
ade_CXXSRC = $(ade_CPU_CXXSRC) $(ade_WIZARD_CXXSRC) $(ade_USER_CXXSRC)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
ade_ASRC = $(ade_CPU_ASRC) $(ade_WIZARD_ASRC) $(ade_USER_ASRC)

# CPU specific flags and options, defined in the CPU definition files.
# Automatically generated by the wizard. PLEASE DO NOT EDIT!
ade_DEBUG_SCRIPT = bertos/prg_scripts/nodebug.sh
ade_PROGRAMMER_CPU = atmega644p
ade_STOPDEBUG_SCRIPT = bertos/prg_scripts/none.sh
ade_MCU = atmega644p
ade_FLASH_SCRIPT = bertos/prg_scripts/avr/flash.sh
ade_STOPFLASH_SCRIPT = bertos/prg_scripts/avr/stopflash.sh
ade_CPU_CPPFLAGS = -Os -Ibertos/cpu/avr/

include $(ade_SRC_PATH)/ade_user.mk
